const fs = require('fs')
let c = fs.readFileSync('app/painel/page.tsx', 'utf8')
c = c.replace("from '../../lib/supabase'", "from '../lib/supabase'")
fs.writeFileSync('app/painel/page.tsx', c, 'utf8')
console.log('Corrigido!')